---
- name: config
  hosts: R3
  connection: local
  gather_facts: no
  tasks:
    - name: configure provider
      set_fact:
        provider:
          username: 
          password: 

    - name: configure top level configuration
      ios_config:
        lines: hostname {{ inventory_hostname }}
        timeout: 30
        provider: "{{provider}}"

  roles:
    - r3_ip
    - r3_ospf
